import { Movement, Equipment } from './types';
import { VIDEO } from './youtube-map';

const watch = (id: string) => `https://www.youtube.com/watch?v=${id}`;

// YouTube demo link helpers.
//
// Every movement points to a specific, *verified* demo video (see
// lib/youtube-map.ts — each id was confirmed live via YouTube's oembed API).
// `yt(query)` is the fallback: a scoped YouTube *search* URL that can never
// 404 and always lands on a relevant demo, used for anything not yet pinned.
const yt = (q: string) =>
  `https://www.youtube.com/results?search_query=${encodeURIComponent('CrossFit ' + q + ' demo')}`;

// Prefer the verified direct video for `key`; otherwise fall back to search.
const vidOr = (key: string, q: string) => (VIDEO[key] ? watch(VIDEO[key]) : yt(q));

// ===== The BUX movement library =====
// Categorized by modality and tagged with the equipment that satisfies them.
// `none` means pure bodyweight. `full_gym` and `park` are treated as wildcards
// in the engine (a full gym / open park has almost everything).
export const MOVEMENTS: Movement[] = [
  // ---------- Monostructural / Cardio ----------
  {
    id: 'run',
    name: 'Run',
    modality: 'cardio',
    equipment: ['none', 'park'],
    youtube: yt('running pacing'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 200,
    unit: 'm',
    load: 0,
    tags: ['monostructural'],
  },
  {
    id: 'shuttle_run',
    name: 'Shuttle Run',
    modality: 'cardio',
    equipment: ['none', 'park'],
    youtube: yt('shuttle run'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 100,
    unit: 'm',
    load: 0,
  },
  {
    id: 'high_knees',
    name: 'High Knees',
    modality: 'cardio',
    equipment: ['none', 'park'],
    youtube: yt('high knees'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 40,
    unit: 'reps',
    load: 0,
  },
  {
    id: 'double_unders',
    name: 'Double Unders',
    modality: 'cardio',
    equipment: ['jump_rope', 'full_gym'],
    youtube: yt('double unders'),
    levels: ['intermediate', 'advanced'],
    baseReps: 40,
    unit: 'reps',
    load: 0,
    scaling: 'מתחילים: 60 דילוגים רגילים (Single Unders) במקום.',
  },
  {
    id: 'single_unders',
    name: 'Single Unders',
    modality: 'cardio',
    equipment: ['jump_rope', 'full_gym'],
    youtube: yt('single unders jump rope'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 60,
    unit: 'reps',
    load: 0,
  },
  {
    id: 'row_cal',
    name: 'Row',
    modality: 'cardio',
    equipment: ['cardio_machine', 'full_gym'],
    youtube: yt('rowing technique'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 12,
    unit: 'cal',
    load: 0,
  },
  {
    id: 'bike_cal',
    name: 'Echo/Assault Bike',
    modality: 'cardio',
    equipment: ['cardio_machine', 'full_gym'],
    youtube: yt('assault bike'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 10,
    unit: 'cal',
    load: 0,
  },
  {
    id: 'ski_cal',
    name: 'SkiErg',
    modality: 'cardio',
    equipment: ['cardio_machine', 'full_gym'],
    youtube: yt('skierg'),
    levels: ['intermediate', 'advanced'],
    baseReps: 12,
    unit: 'cal',
    load: 0,
  },
  {
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    modality: 'cardio',
    equipment: ['none', 'park'],
    youtube: yt('mountain climbers'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 40,
    unit: 'reps',
    load: 0,
  },

  // ---------- Gymnastics / Bodyweight ----------
  {
    id: 'air_squat',
    name: 'Air Squat',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('air squat'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 20,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'pushup',
    name: 'Push-up',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('push up'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 15,
    unit: 'reps',
    load: 1,
    scaling: 'מתחילים: שכיבות סמיכה על הברכיים או בזווית מול ספסל.',
  },
  {
    id: 'situp',
    name: 'Sit-up',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('AbMat sit up'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 20,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'burpee',
    name: 'Burpee',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('burpee'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 12,
    unit: 'reps',
    load: 2,
    scaling: 'מתחילים: בצעו את הבורפי בקצב מבוקר, אפשר בלי קפיצה בסוף.',
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('walking lunge'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 20,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'jumping_jacks',
    name: 'Jumping Jacks',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('jumping jacks'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 40,
    unit: 'reps',
    load: 0,
  },
  {
    id: 'hollow_hold',
    name: 'Hollow Hold',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('hollow hold'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 30,
    unit: 'sec',
    load: 1,
  },
  {
    id: 'plank',
    name: 'Plank Hold',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('plank hold'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 45,
    unit: 'sec',
    load: 1,
  },
  {
    id: 'pullup',
    name: 'Pull-up',
    modality: 'gymnastics',
    equipment: ['pullup_bar', 'rings', 'full_gym', 'park'],
    youtube: yt('pull up'),
    levels: ['intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 2,
    scaling: 'מתחילים: Ring Rows או מתח בעזרת גומיית התנגדות.',
  },
  {
    id: 'chinup',
    name: 'Chin-up',
    modality: 'gymnastics',
    equipment: ['pullup_bar', 'full_gym', 'park'],
    youtube: yt('chin up'),
    levels: ['intermediate', 'advanced'],
    baseReps: 8,
    unit: 'reps',
    load: 2,
    scaling: 'מתחילים: בעזרת גומיית התנגדות או אחיזה איזומטרית למעלה.',
  },
  {
    id: 'toes_to_bar',
    name: 'Toes-to-Bar',
    modality: 'gymnastics',
    equipment: ['pullup_bar', 'full_gym', 'park'],
    youtube: yt('toes to bar'),
    levels: ['advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 2,
    scaling: 'סקיילינג: Knees-to-Elbow או הרמות ברכיים תלוי על המוט (Knee Raises).',
  },
  {
    id: 'knees_to_elbow',
    name: 'Knees-to-Elbow',
    modality: 'gymnastics',
    equipment: ['pullup_bar', 'full_gym', 'park'],
    youtube: yt('knees to elbow'),
    levels: ['intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 2,
    scaling: 'מתחילים: הרמות ברכיים תלוי על המוט.',
  },
  {
    id: 'ring_row',
    name: 'Ring Row',
    modality: 'gymnastics',
    equipment: ['rings', 'full_gym'],
    youtube: yt('ring row'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 12,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'ring_dip',
    name: 'Ring Dip',
    modality: 'gymnastics',
    equipment: ['rings', 'full_gym'],
    youtube: yt('ring dip'),
    levels: ['advanced'],
    baseReps: 8,
    unit: 'reps',
    load: 2,
    scaling: 'סקיילינג: Bench Dips או דחיקות על קרקע.',
  },
  {
    id: 'box_jump',
    name: 'Box Jump',
    modality: 'gymnastics',
    equipment: ['box', 'full_gym'],
    youtube: yt('box jump'),
    levels: ['intermediate', 'advanced'],
    baseReps: 15,
    unit: 'reps',
    load: 2,
    scaling: 'מתחילים: Box Step-ups (עלייה ברגל אחת בכל פעם).',
  },
  {
    id: 'box_step_up',
    name: 'Box Step-up',
    modality: 'gymnastics',
    equipment: ['box', 'full_gym', 'park'],
    youtube: yt('box step up'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 20,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'handstand_pushup',
    name: 'Handstand Push-up',
    modality: 'gymnastics',
    equipment: ['none', 'full_gym'],
    youtube: yt('handstand push up'),
    levels: ['advanced'],
    baseReps: 8,
    unit: 'reps',
    load: 3,
    scaling: 'סקיילינג: Pike Push-up עם הרגליים על תיבה/ספסל.',
  },
  {
    id: 'pike_pushup',
    name: 'Pike Push-up',
    modality: 'gymnastics',
    equipment: ['none', 'box', 'full_gym'],
    youtube: yt('pike push up'),
    levels: ['intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 2,
  },
  {
    id: 'wall_walk',
    name: 'Wall Walk',
    modality: 'gymnastics',
    equipment: ['none', 'full_gym'],
    youtube: yt('wall walk'),
    levels: ['intermediate', 'advanced'],
    baseReps: 4,
    unit: 'reps',
    load: 3,
  },
  {
    id: 'broad_jump',
    name: 'Broad Jump',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('broad jump'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'jumping_lunge',
    name: 'Jumping Lunge',
    modality: 'gymnastics',
    equipment: ['none', 'park'],
    youtube: yt('jumping lunge'),
    levels: ['intermediate', 'advanced'],
    baseReps: 20,
    unit: 'reps',
    load: 2,
  },

  // ---------- Weightlifting: Dumbbells ----------
  {
    id: 'db_thruster',
    name: 'Dumbbell Thruster',
    modality: 'weightlifting',
    equipment: ['dumbbells', 'full_gym'],
    youtube: yt('dumbbell thruster'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 12,
    unit: 'reps',
    load: 3,
    scaling: 'בחרו משקל שמאפשר לבצע את כל החזרות רצופות בטכניקה נקייה.',
  },
  {
    id: 'db_snatch',
    name: 'Dumbbell Snatch',
    modality: 'weightlifting',
    equipment: ['dumbbells', 'full_gym'],
    youtube: yt('dumbbell snatch'),
    levels: ['intermediate', 'advanced'],
    baseReps: 14,
    unit: 'reps',
    load: 2,
    scaling: 'מתחילים: משקל קל וטכניקה לפני קצב. מתחלפים יד כל חזרה.',
  },
  {
    id: 'devil_press',
    name: 'Devil Press',
    modality: 'weightlifting',
    equipment: ['dumbbells', 'full_gym'],
    youtube: yt('devil press'),
    levels: ['intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 3,
    scaling: 'מתחילים: Dumbbell Burpee — בורפי ואז הרמה מעל הראש בנפרד.',
  },
  {
    id: 'db_push_press',
    name: 'Dumbbell Push Press',
    modality: 'weightlifting',
    equipment: ['dumbbells', 'full_gym'],
    youtube: yt('dumbbell push press'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 12,
    unit: 'reps',
    load: 2,
  },
  {
    id: 'db_goblet_squat',
    name: 'Goblet Squat',
    modality: 'weightlifting',
    equipment: ['dumbbells', 'kettlebell', 'full_gym'],
    youtube: yt('goblet squat'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 15,
    unit: 'reps',
    load: 2,
  },
  {
    id: 'db_renegade_row',
    name: 'Renegade Row',
    modality: 'weightlifting',
    equipment: ['dumbbells', 'full_gym'],
    youtube: yt('renegade row'),
    levels: ['intermediate', 'advanced'],
    baseReps: 12,
    unit: 'reps',
    load: 2,
  },
  {
    id: 'db_farmers_carry',
    name: "Farmer's Carry",
    modality: 'weightlifting',
    equipment: ['dumbbells', 'kettlebell', 'full_gym'],
    youtube: yt('farmers carry'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 40,
    unit: 'm',
    load: 1,
  },

  // ---------- Weightlifting: Kettlebell ----------
  {
    id: 'kb_swing',
    name: 'Kettlebell Swing',
    modality: 'weightlifting',
    equipment: ['kettlebell', 'full_gym'],
    youtube: yt('russian kettlebell swing'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 20,
    unit: 'reps',
    load: 2,
    scaling: 'מתחילים: Russian Swing עד גובה הכתפיים. מתקדמים: American Swing מעל הראש.',
  },
  {
    id: 'kb_goblet_clean',
    name: 'Kettlebell Clean',
    modality: 'weightlifting',
    equipment: ['kettlebell', 'full_gym'],
    youtube: yt('kettlebell clean'),
    levels: ['intermediate', 'advanced'],
    baseReps: 14,
    unit: 'reps',
    load: 2,
  },
  {
    id: 'kb_snatch',
    name: 'Kettlebell Snatch',
    modality: 'weightlifting',
    equipment: ['kettlebell', 'full_gym'],
    youtube: yt('kettlebell snatch'),
    levels: ['advanced'],
    baseReps: 14,
    unit: 'reps',
    load: 2,
    scaling: 'מתחילים: Kettlebell Swing במקום.',
  },
  {
    id: 'kb_thruster',
    name: 'Kettlebell Thruster',
    modality: 'weightlifting',
    equipment: ['kettlebell', 'full_gym'],
    youtube: yt('kettlebell thruster'),
    levels: ['intermediate', 'advanced'],
    baseReps: 14,
    unit: 'reps',
    load: 3,
  },
  {
    id: 'kb_turkish_getup',
    name: 'Turkish Get-up',
    modality: 'weightlifting',
    equipment: ['kettlebell', 'dumbbells', 'full_gym'],
    youtube: yt('turkish get up'),
    levels: ['intermediate', 'advanced'],
    baseReps: 6,
    unit: 'reps',
    load: 2,
  },

  // ---------- Weightlifting: Barbell ----------
  {
    id: 'bb_thruster',
    name: 'Barbell Thruster',
    modality: 'weightlifting',
    equipment: ['barbell', 'full_gym'],
    youtube: yt('barbell thruster'),
    levels: ['intermediate', 'advanced'],
    baseReps: 12,
    unit: 'reps',
    load: 3,
    scaling: 'Rx: 43/30 ק״ג. מתחילים: מוט ריק או PVC לטכניקה.',
  },
  {
    id: 'bb_deadlift',
    name: 'Deadlift',
    modality: 'weightlifting',
    equipment: ['barbell', 'full_gym'],
    youtube: yt('barbell deadlift'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 3,
    scaling: 'שמרו על גב נייטרלי. בחרו משקל מאתגר אך בטוח.',
  },
  {
    id: 'bb_clean',
    name: 'Power Clean',
    modality: 'weightlifting',
    equipment: ['barbell', 'full_gym'],
    youtube: yt('power clean'),
    levels: ['intermediate', 'advanced'],
    baseReps: 8,
    unit: 'reps',
    load: 3,
    scaling: 'מתחילים: Hang Power Clean ממוט קל.',
  },
  {
    id: 'bb_snatch',
    name: 'Power Snatch',
    modality: 'weightlifting',
    equipment: ['barbell', 'full_gym'],
    youtube: yt('power snatch'),
    levels: ['advanced'],
    baseReps: 7,
    unit: 'reps',
    load: 3,
    scaling: 'מתחילים: Hang Power Snatch או Dumbbell Snatch.',
  },
  {
    id: 'bb_front_squat',
    name: 'Front Squat',
    modality: 'weightlifting',
    equipment: ['barbell', 'full_gym'],
    youtube: yt('front squat'),
    levels: ['intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 3,
  },
  {
    id: 'bb_back_squat',
    name: 'Back Squat',
    modality: 'weightlifting',
    equipment: ['barbell', 'full_gym'],
    youtube: yt('back squat'),
    levels: ['intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 3,
  },
  {
    id: 'bb_push_press',
    name: 'Push Press',
    modality: 'weightlifting',
    equipment: ['barbell', 'full_gym'],
    youtube: yt('push press'),
    levels: ['intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 3,
  },
  {
    id: 'bb_overhead_press',
    name: 'Strict Press',
    modality: 'weightlifting',
    equipment: ['barbell', 'full_gym'],
    youtube: yt('shoulder press'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 10,
    unit: 'reps',
    load: 3,
  },

  // ---------- Wall Ball / Medball (full gym) ----------
  {
    id: 'wall_ball',
    name: 'Wall Ball',
    modality: 'weightlifting',
    equipment: ['full_gym'],
    youtube: yt('wall ball'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 15,
    unit: 'reps',
    load: 2,
    scaling: 'Rx: 9/6 ק״ג למטרה 10/9 רגל. מתחילים: כדור קל יותר ומטרה נמוכה.',
  },

  // ---------- Resistance Bands ----------
  {
    id: 'band_pull_apart',
    name: 'Band Pull-apart',
    modality: 'weightlifting',
    equipment: ['bands', 'full_gym'],
    youtube: yt('band pull apart'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 20,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'band_press',
    name: 'Band Overhead Press',
    modality: 'weightlifting',
    equipment: ['bands', 'full_gym'],
    youtube: yt('resistance band shoulder press'),
    levels: ['beginner', 'intermediate'],
    baseReps: 18,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'band_row',
    name: 'Band Bent-over Row',
    modality: 'weightlifting',
    equipment: ['bands', 'full_gym'],
    youtube: yt('resistance band row'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 18,
    unit: 'reps',
    load: 1,
  },
  {
    id: 'band_good_morning',
    name: 'Band Good Morning',
    modality: 'weightlifting',
    equipment: ['bands', 'full_gym'],
    youtube: yt('band good morning'),
    levels: ['beginner', 'intermediate', 'advanced'],
    baseReps: 18,
    unit: 'reps',
    load: 1,
  },
];

// Override each movement's link with its verified direct video where we have
// one (keyed by movement id). Anything not yet pinned keeps its search URL.
for (const m of MOVEMENTS) {
  if (VIDEO[m.id]) m.youtube = watch(VIDEO[m.id]);
}

// ===== Warm-up movement pool (Hebrew-facing detail kept generic) =====
export interface WarmupMove {
  name: string;
  detail: string;
  youtube: string;
  // If set, this move needs that equipment — the engine drops it from the
  // pool when the athlete doesn't have it (so a bodyweight-only warm-up never
  // prescribes e.g. Scapular Pull-ups with no bar around).
  needs?: Equipment;
}

export const WARMUP_POOL: WarmupMove[] = [
  { name: 'Jumping Jacks', detail: '30 שניות', youtube: vidOr('jumping_jacks', 'jumping jacks') },
  { name: 'Arm Circles', detail: '30 שניות (קדימה ואחורה)', youtube: vidOr('wu:arm_circles', 'arm circles warm up') },
  { name: 'Leg Swings', detail: '10 לכל רגל', youtube: vidOr('wu:leg_swings', 'leg swings warm up') },
  { name: 'World’s Greatest Stretch', detail: '5 לכל צד', youtube: vidOr('wu:worlds_greatest', 'worlds greatest stretch') },
  { name: 'Inchworm', detail: '8 חזרות', youtube: vidOr('wu:inchworm', 'inchworm warm up') },
  { name: 'Air Squat', detail: '15 חזרות', youtube: vidOr('air_squat', 'air squat') },
  { name: 'Spiderman Lunge', detail: '8 לכל צד', youtube: vidOr('wu:spiderman_lunge', 'spiderman lunge') },
  { name: 'Hip Circles', detail: '10 לכל כיוון', youtube: vidOr('wu:hip_circles', 'hip circles mobility') },
  { name: 'Scapular Pull-ups', detail: '8 חזרות', youtube: vidOr('wu:scap_pullups', 'scapular pull ups'), needs: 'pullup_bar' },
  { name: 'Shoulder Pass-throughs', detail: '10 חזרות (מקל או מגבת)', youtube: vidOr('wu:pass_throughs', 'shoulder pass throughs') },
  { name: 'High Knees', detail: '30 שניות', youtube: vidOr('high_knees', 'high knees') },
  { name: 'Cossack Squat', detail: '6 לכל צד', youtube: vidOr('wu:cossack_squat', 'cossack squat') },
];

// ===== Cool-down / mobility pool =====
export const COOLDOWN_POOL: WarmupMove[] = [
  { name: 'Child’s Pose', detail: '60 שניות', youtube: vidOr('cd:childs_pose', 'childs pose stretch') },
  { name: 'Pigeon Stretch', detail: '45 שניות לכל צד', youtube: vidOr('cd:pigeon', 'pigeon stretch') },
  { name: 'Couch Stretch', detail: '45 שניות לכל צד', youtube: vidOr('cd:couch', 'couch stretch') },
  { name: 'Forward Fold', detail: '60 שניות', youtube: vidOr('cd:forward_fold', 'standing forward fold') },
  { name: 'Cat-Cow', detail: '8 חזרות', youtube: vidOr('cd:cat_cow', 'cat cow stretch') },
  { name: 'Thread the Needle', detail: '30 שניות לכל צד', youtube: vidOr('cd:thread_needle', 'thread the needle stretch') },
  { name: 'Cross-body Shoulder Stretch', detail: '30 שניות לכל צד', youtube: vidOr('cd:cross_shoulder', 'cross body shoulder stretch') },
  { name: 'Seated Hamstring Stretch', detail: '45 שניות לכל צד', youtube: vidOr('cd:seated_ham', 'seated hamstring stretch') },
  { name: 'Quad Stretch', detail: '30 שניות לכל צד', youtube: vidOr('cd:quad', 'standing quad stretch') },
  { name: 'Box Breathing', detail: '60 שניות (4-4-4-4)', youtube: vidOr('cd:box_breathing', 'box breathing recovery') },
];
